name: f_timeline
description: A so easy to use flutter package to show Timeline in flutter
version: 0.5.0
homepage: https://github.com/Istiak-Ahmed78/f_timeline

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  plugin:
    platforms:

      some_platform:
        pluginClass: somePluginClass
  